### ISSUE TITLE
复制为markdown格式脚本，添加功能 可选是否复制为markdown格式

### ISSUE THREAD

**Issue by wfnetworks** [nameldk/user-script#2]
https://greasyfork.org/scripts/370299-%E5%A4%8D%E5%88%B6%E4%B8%BAmarkdown%E6%A0%BC%E5%BC%8F
您好这个脚本是否可以添加，只复制正文和图片，无需复制为markdown格式。

**Comment by nameldk** [comment]
这个脚本的用途是复制成markdown格式的，只复制正文和图片的话，您可以直接用鼠标选中复制即可。
